version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development