[package]
name = "protoxy"
version = "0.7.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "protoxy"
crate-type = ["cdylib"]

[dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
prost = "0.14.0"
prost-types = "0.14.0"
protobuf = "3.7.2"
protox = "0.8.0"
pyo3 = "0.25.1"
thiserror = "2.0.12"
